# Generated by Django 3.0.4 on 2020-04-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['name', 'from_city'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
        migrations.RenameField(
            model_name='train',
            old_name='travele_time',
            new_name='travel_time',
        ),
    ]
