# Generated by Django 3.0.4 on 2020-04-22 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('comment_origin', models.IntegerField(default=0, verbose_name='подкомментарий')),
                ('lvl', models.IntegerField(default=0, verbose_name='уровень ветки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('blog_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.Blog', verbose_name='Комментарий к блогу')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['create_time'],
            },
        ),
    ]
