# Generated by Django 3.0.4 on 2020-03-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='music_album',
        ),
    ]
