# Generated by Django 3.0.4 on 2020-03-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20200331_1842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
