# Generated by Django 3.0.4 on 2020-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20200331_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='foto',
            field=models.CharField(max_length=250, null=True, verbose_name='Фото'),
        ),
    ]
