# Generated by Django 3.0.6 on 2020-05-19 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(verbose_name='Комментарий')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('new_message', models.BooleanField(default=True)),
                ('interlocutors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['create_time'],
            },
        ),
    ]
