# Generated by Django 3.0.6 on 2020-05-20 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_chat', '0002_auto_20200519_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
