# Generated by Django 3.0.6 on 2020-05-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0004_auto_20200520_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_message',
            name='author',
        ),
    ]
